// schemas/registration.js
module.exports = {
    Registration: {
        type: 'object',
        properties: {
            _id: {
                type: 'string',
                format: 'objectid',
                description: 'The autogenerated id of the registration',
                example: '5f3f9c5f6d7a0f0021e9d4b7',
            },
            studentId: {
                type: 'string',
                format: 'objectid',
                description: 'The id of the student associated with the registration',
                example: '5f3f9c5f6d7a0f0021e9d4b7',
            },
            groupId: {
                type: 'string',
                format: 'objectid',
                description: 'The id of the group associated with the registration',
                example: '5f3f9c5f6d7a0f0021e9d4b7',
            },
            date: {
                type: 'string',
                format: 'date',
                description: 'The date of the registration',
                example: '2020-08-20',
            },
            notes: {
                type: 'string',
                description: 'Additional notes for the registration',
                example: 'Late arrival',
            },
            createdAt: {
                type: 'string',
                format: 'date-time',
                description: 'The date and time when the registration was created',
                example: '2020-08-20T20:00:00.000Z',
            },
            updatedAt: {
                type: 'string',
                format: 'date-time',
                description: 'The date and time when the registration was last updated',
                example: '2020-08-20T20:00:00.000Z',
            },
        },
        required: ['studentId', 'groupId', 'date'],
    },
};